fA = float(input("Please input number A"))
fB = float(input("Please input nunber B"))
fC = float(input("Please input number C"))
fD = float(input("Please input number D"))
fTotal = (fA / fB) + (fC / fD)
print(fTotal)